version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: githubusers
      POSTGRES_USER: githubusers
      POSTGRES_DB: githubusers
